HEAD http://localhost:3001/ HTTP/1.1

###
GET http://localhost:3001/ HTTP/1.1

###
GET http://localhost:3001/api/notes HTTP/1.1

###
GET http://localhost:3001/api/notes/64d92d89114a87c1e60f9742 HTTP/1.1

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "Very very new note",
    "imprtant": true,
    "userId": "653d0b18964dd240fe27ed4b"
}

###
DELETE http://localhost:3001/api/notes/653ac5f274f1e7129e5557e6 HTTP/1.1

###
PUT http://localhost:3001/api/notes/64da8da94cb1ca604a9dda24 HTTP/1.1
content-type: application/json

{
    "content": "VS code REST client perfect handy tool and other tools",
    "imprtant": false
}

###
GET http://localhost:3001/api/users/ HTTP/1.1

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "rootik",
    "name": "superadmin",
    "password": "admin"
}

